# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

# name: Node.js Package

# on:
#   release:
#     types: [created]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 18
#       - run: npm ci

#   publish-npm:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 16
#           registry-url: https://registry.npmjs.org/
#       - run: npm ci
#       - run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.npm_token}}

name: Autodeploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Какую ветку отправить?'
        default: 'main'
        required: true

jobs:
  autodeploy:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout ${{ github.event.inputs.branch }}
        uses: actions/checkout@v4
        with:
          # ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.PAT_EXPIRING }}

      - name: Connect to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd tg-bot-js
            
            git fetch
            git checkout ${{ github.event.inputs.branch }}
            git pull
            
            npm i
            npm run restart
